repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
repos:
-   repo: https://github.com/saily/pre-commit-yapf-isort
    rev: 598ff67
    hooks:
    -   id: yapf-isort
